### ISSUE TITLE
Update/Patch issue

### ISSUE THREAD

**Issue by sml-40** [ethandb23/fitness-tracker#19]
Our update/patch function is not returning the correct error message. Also I am unsure as to what data I should be putting into postman in order to update.

// router.patch("/api/workout/:id", (req, res) => {
// 	Workout.findById(req.params.id)
// 		.then((workouts) => {
// 			if (workouts) {
// 				//Pass the result of Mongooses `.update` method to the next `.then` on the promise chain
// 				return workouts.update(req.body.workouts);
// 			} else {
// 				//If we couldn't find a document with the matching ID
// 				res.status(404).json({
// 					error: {
// 						name: "DocumentNotFoundError",
// 						message: "The provided ID doesn't match any documents",
// 					},
// 				});
// 			}
// 		})
// 		.then(() => {
// 			//If the update succeeded, return 204(no content) and no JSON
// 			res.status(204).end();
// 		})
// 		// catch any errors that might occur
// 		.catch((error) => {
// 			res.status(500).json({ error: error });
// 		});
// });

**Comment by usmanbashir** [comment]
Hey @sml-40, can you explain what you mean by the following?

> Our update/patch function is not returning the correct error message.

As this rote is not supposed to send any content back except for a status code of 204 if the update was successful.

Also, I'm not sure what columns you have on your `Workout` model. But based on your code, have you tried sending them in the following format over Postman?

```json
{
  "workouts": {
    "columnName": "columnValue"
  }
}
```

**Comment by usmanbashir** [comment]
@sml-40 Make sure you are making a PATCH request from Postman. And if that is not it, try adding some `console.log` statements throughout the route to see how far it works and what is stopping it.
