### ISSUE TITLE
Axios call for username

### ISSUE THREAD

**Issue by sml-40** [ethandb23/fitness-tracker#38]
Hi, I have been working on the axios call for the username login.  Here is my code:

	onSubmit = (e) => {
		e.preventDefault();

		const user = {
			username: this.state.username,
		};
		console.log(user);

		console.log("Username from state:", this.state.username);

		axios
			.get(`http://localhost:5001/user`)
			.then((response) => {
				// Get the user data from the response
				const users = response.data.user;

				console.log("Users:", users);
				// Find the user with the matching username
				const user = users.find(
					(user) => user.username === this.state.username
				);

				// Check if the user was found
				if (user) {
					console.log("User found:", user);
				} else {
					// username does not exist in the database
					console.log("User not found");
				}
			})
			.catch((err) => {
				console.error("Error: ", err);
			});

		this.setState({
			username: "",
		});
		// window.location = "/";
	};

I am getting this response in the console, showing that the state for username matches the username in database, but my code must be wrong because it keeps saying 'user not found':

{username: 'sel123'}
UserLogin.js:33 Username from state: sel123
UserLogin.js:41 Users: (4) [{…}, {…}, {…}, {…}]0: {_id: '63e5008bc7baadf23d7476e7', firstName: 'Usman', lastName: 'Bashir', username: 'Us-dog', password: 'gains123', …}1: {_id: '63e5008bc7baadf23d7476e8', firstName: 'Joan', lastName: 'Kalanzi', username: 'JKal', password: 'joan1', …}2: {_id: '63e7f25ec4e2b7db54ff11dd', firstName: 'Ana', lastName: 'Solcan', username: 'solcana', password: '123456', …}3: {_id: '63e7f25ec4e2b7db54ff11dc', firstName: 'Selina', lastName: 'Lavery', username: 'sel123', password: '123456', …}length: 4[[Prototype]]: Array(0)
UserLogin.js:52 User not found

**Comment by JoanKalanzi** [comment]
I spoke to @sml-40 regarding the issue; she needed to add the login functionality in the backend. I gave feedback and documentation on how to Set up JWT authentication. I will follow up on this issue tomorrow.

**Comment by usmanbashir** [comment]
Thanks @JoanKalanzi, and @sml-40 did you guys not set up a login already? Maybe it has been implemented. Please make sure to check in with the whole team.

**Comment by sml-40** [comment]
I had set up all the CRUD routes, but i don't remember doing a specific login route in the lesson, so didn't realise. I did speak with team members before we did the issue, so it's not something i've missed that is already there, i think! 

My bad, though, will look it up now and get it created.

**Comment by sml-40** [comment]
issue resolved
